import cv2 as cv
import numpy as np

src = cv.imread("japaneseflowers.jpg", 1)
if src is None:
    print("missing image")
else:
    gray = cv.cvtColor(src, cv.COLOR_RGB2GRAY)
    	#apply thresholdin 
    ret,mask = cv.threshold(gray,0,255,cv.THRESH_BINARY_INV+cv.THRESH_OTSU) 
	#apply AND operation on image and mask generated by thresholding
    final = cv.bitwise_and(gray,gray,mask = mask) 

    cv.imshow("Original", gray)
    cv.imshow("adaptive", final)            
                
                
